services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data

  mlflow:
    build: .
    depends_on:
      - minio
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - mlflow_data:/app/mlflow_data
    ports:
      - "5000:5000"
      - "8000:8000"
    command: >
      bash -c "
      mlflow server 
      --backend-store-uri sqlite:///mlflow_data/mlflow.db 
      --default-artifact-root s3://mlflow/ 
      --host 0.0.0.0 
      --port 5000 &
      sleep 10 &&
      uvicorn src.predict_api:app --host 0.0.0.0 --port 8000 --reload
      "

  airflow:
    image: apache/airflow:2.9.0-python3.11
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__SECRET_KEY: thisissecret
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'True'
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install mlflow && 
               airflow db init && 
               airflow db migrate && 
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.org || true &&
               exec airflow webserver --port 8080"

volumes:
  minio:
  mlflow_data:
