name: Notify Slack on All Repository Events
on:
  issues:
    types: [opened, edited, deleted, labeled, unlabeled, closed, reopened]
  issue_comment:
    types: [created, edited, deleted]
  pull_request:
    types: [opened, edited, closed, reopened, review_requested, labeled, unlabeled]
  push:
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]
  release:
    types: [published, unpublished, edited]
  workflow_run:
    workflows: ["*"] # 모든 워크플로우 실행 완료 시
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          EVENT_TYPE="${{ github.event_name }}"
          REPO="${{ github.repository }}"
          case "$EVENT_TYPE" in
            "issues")
              MESSAGE="Issue #${{ github.event.issue.number }} (${{ github.event.action }}) in $REPO: ${{ github.event.issue.title }} by ${{ github.event.issue.user.login }}"
              ;;
            "issue_comment")
              MESSAGE="Comment (${{ github.event.action }}) on issue/PR #${{ github.event.issue.number }} in $REPO by ${{ github.event.comment.user.login }}: ${{ github.event.comment.body }}"
              ;;
            "pull_request")
              MESSAGE="Pull Request #${{ github.event.pull_request.number }} (${{ github.event.action }}) in $REPO: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}"
              ;;
            "push")
              MESSAGE="Push to $REPO on branch ${{ github.event.ref }} by ${{ github.actor }}"
              ;;
            "pull_request_review")
              MESSAGE="PR Review (${{ github.event.action }}) on #${{ github.event.pull_request.number }} in $REPO by ${{ github.event.review.author.login }}"
              ;;
            "pull_request_review_comment")
              MESSAGE="PR Review Comment (${{ github.event.action }}) on #${{ github.event.pull_request.number }} in $REPO by ${{ github.event.comment.user.login }}: ${{ github.event.comment.body }}"
              ;;
            "release")
              MESSAGE="Release (${{ github.event.action }}) in $REPO: ${{ github.event.release.tag_name }} by ${{ github.event.release.author.login }}"
              ;;
            "workflow_run")
              MESSAGE="Workflow run (${{ github.event.workflow_run.conclusion }}) in $REPO: ${{ github.event.workflow_run.name }}"
              ;;
            *)
              MESSAGE="Event $EVENT_TYPE in $REPO"
              ;;
          esac
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\": \"$MESSAGE\"}" \
            $SLACK_WEBHOOK_URL
